DishDecoderApp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from DishDecoderApp import views
from django.contrib.auth.decorators import login_required
from DishDecoderApp.models import *
from .forms import Main_page_form, Create_user_form, Change_password_form , Change_email_form
from DishDecoderApp.views import *
urlpatterns = [
    path('',main_url.as_view(), name = "home"),
    path('login/',login_page_url.as_view(), name="login"),
    path('register/',register_page_url.as_view(), name="register"),
    path('logout/',logout_url.as_view(), name="logout"),
    path('recipes/',list_data_url.as_view(template_name="DishDecoderApp/recipes.html",baseurl="/recipe/", searchedObject=Recipes,title_page="Recipes"), name="recipes"),
    path('recipe/<int:recipeid>', recipe_profile_url.as_view(), name="recipe"),
    path('basicproducts/',list_data_url.as_view(template_name="DishDecoderApp/basicproducts.html",baseurl="/basicproduct/", searchedObject=BasicProducts,title_page="Basic Products"), name="basicproducts"),
    path('basicproduct/<int:basicproductid>',basicproduct_profile_url.as_view(), name="basicproduct"),
    path('nutrients/',list_data_url.as_view(template_name="DishDecoderApp/nutrients.html",baseurl="/nutrient/", searchedObject=Nutrients,title_page="Nutrients"), name="nutrients"),
    path('nutrient/<int:nutrientid>',nutrient_profile_url.as_view(), name="nutrient"),
    path('profile/',user_profile_url.as_view()),
    path('profile/change_password',change_data_url.as_view(template_name="DishDecoderApp/change_password.html",form_function=Change_password_form,title_page="Change password"), name="changepass"),
    path('profile/change_email',change_data_url.as_view(template_name="DishDecoderApp/change_email.html",form_function=Change_email_form,title_page="Change email"), name="changemail"),
    #path('autocomplete/', autocomplete_test_url.as_view(), name='autocomplete_test'),
    path('extrecipe/', external_recipe_url.as_view(), name='extrecipe'),
    path('createrecipe/',create_recipe_url.as_view(), name="createrecipe"),
    path('listedit/',list_recipes_edit_url.as_view(), name="listeditrecipe"),
    path('edit/<int:recipeid>',edit_recipe_url.as_view(), name="edit"),
    path('erase/',erase_recipe_url.as_view(),name="listeraserecipe"),
    #path('erase/<int:recipeid>',erase_recipe_url.as_view(),name="erase"),
]

DishDecoderProject/DishDecoderProject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

DishDecoderApp/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.conf import settings
from django.contrib.auth.models import User
from .models import Ratings, Recipes
#Here we create the views for the forms

class Autocomplete_form(forms.Form):
    recipe_title = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder': 'Type something here'}))
    recipe_href = forms.CharField(widget = forms.HiddenInput(), required = False)
    recipe_ing = forms.CharField(widget = forms.HiddenInput(), required = False)


class Main_page_form(forms.Form):
    request_objective = forms.ChoiceField(choices=(("1","Recipe"),("2","BasicProduct"),("3","Nutrient")),widget=forms.RadioSelect,label='')
    item_name = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder': 'Type something here'}))

class Create_user_form(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class Change_password_form(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password','new_password','new_password2']

class Change_email_form(forms.Form):
    new_email1 = forms.EmailField(label="New email address",widget=forms.EmailInput)
    new_email2 = forms.EmailField(label="New email confirmation",widget=forms.EmailInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(Change_email_form,self).__init__(*args,**kwargs)

    def clean_new_email1(self):
        old_email = self.user.email
        new_email1 = self.cleaned_data.get('new_email1')
        if new_email1 and old_email:
            if new_email1 == old_email:
                raise forms.ValidationError("This email address its already define",code="Same email")
        return new_email1

    def clean_new_email2(self):
        new_email1 = self.cleaned_data.get('new_email1')
        new_email2 = self.cleaned_data.get('new_email2')
        if new_email1 and new_email2:
            if new_email1 != new_email2:
                raise forms.ValidationError("The emails you have written do not match",code="mismatch")
        return new_email2

    def save(self, commit=True):
        email = self.cleaned_data["new_email1"]
        self.user.email = email
        if commit:
            self.user.save()
        return self.user
    class Meta:
        fields = ['new_email1','new_email2']
    
class Comments_form(forms.ModelForm):
    class Meta:
        model = Ratings
        fields = ['rating','desc']

class Create_recipe_form(forms.ModelForm):
    class Meta:
        model = Recipes
        fields = ['name','steps',]

class Add_products_form(forms.ModelForm):
    class Meta:
        model = Recipe_Product
        fields = ['id_product','quantity']
        

class erase_recipe_form(forms.Form):
    recipes=forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple,queryset=None)
    def __init__(self, user, *args, **kwargs):
        super(erase_recipe_form, self).__init__(*args,**kwargs)
        self.fields['recipes'].queryset = Recipes.objects.filter(author=user).all()

DishDecoderApp/views.py
from django.conf import settings

from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse,HttpResponseForbidden,HttpResponseBadRequest,HttpResponseNotAllowed,HttpResponseNotFound
from .forms import Main_page_form, Create_user_form, Change_password_form , Change_email_form, Comments_form
from .forms import *
from django.forms import formset_factory
from .forms import Main_page_form, Create_user_form, Change_password_form , Change_email_form, Autocomplete_form
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.views import View
from django.core.exceptions import ValidationError
from django.views.defaults import *
from django.db import *
from urllib.parse import urlencode
from DishDecoderApp.models import *
import random


# GET: Show the principal page, and redirects the search depending on what the user selects
class main_url(View):
    template_name = "DishDecoderApp/main.html"
    form = Main_page_form()
    aform = Autocomplete_form
    def get(self,req):
        template_data = {}
        template_data['form']=self.form
        template_data['aform'] = self.aform
        template_data['title_page']='Dish Decoder'
        template_data['api_key'] = settings.API_KEY
        return render(req, self.template_name,template_data)

    def post(self,req):
        from django.core.exceptions import ValidationError
        external_recipe_title = req.POST.get('recipe_title')
        if external_recipe_title:
            try:
                url = self._autocomplete(req, external_recipe_title)
            except ValidationError:
                return page_not_found(req, exception=None)
        else:
            radioptchoice = str(req.POST.get('request_objective'))
            searched_data = str(req.POST.get('item_name'))
            query_string = urlencode({'search':searched_data})
            if radioptchoice == '1':
                base_url = '/recipes/'
            elif radioptchoice == '2':
                base_url = '/basicproducts/'
            elif radioptchoice == '3':
                base_url = '/nutrients/'
            url = '{}?{}'.format(base_url,query_string)
        return redirect(url)
    
    def _autocomplete(self, req, external_recipe_title):
        from django.core.validators import URLValidator
        external_recipe_href = req.POST.get('recipe_href')
        external_recipe_ing = req.POST.get('recipe_ing')

        validate = URLValidator()
        validate(external_recipe_href)
        query_string = urlencode({'title' : str(external_recipe_title), 
                        'href' : str(external_recipe_href), 
                        'ing' : str(external_recipe_ing)})
        base_url = '/extrecipe'
        print("---",external_recipe_href,"---",external_recipe_ing, "---")
        url = '{}?{}'.format(base_url, query_string)
        return url            
        
        

    
#def main_url(req):
#    template_name="DishDecoderApp/main.html"
#    template_data = {}
#    if req.method == 'POST':
#        radioptchoice = str(req.POST.get('request_objective'))
#        searched_data = str(req.POST.get('item_name'))
#        query_string = urlencode({'search':searched_data})
#        if radioptchoice == '1':
#            base_url = '/recipes/'
#        elif radioptchoice == '2':
#            base_url = '/basicproducts/'
#        elif radioptchoice == '3':
#            base_url = '/nutrients/'
#        url = '{}?{}'.format(base_url,query_string)
#        return redirect(url)
#    form = Main_page_form()
#    template_data['form']=form
#    template_data['title_page']='Dish Decoder'
#    return render(req, template_name,template_data)

#GET : shows the registrations form
#POST : proves that the data introduced is correct, creates the user and redirects the user to log in page

class register_page_url(View):
    template_name = "DishDecoderApp/register.html"
    def get(self, req):
        self.form = Create_user_form()
        template_data = {}
        if not req.user.is_authenticated:
            template_data['reg_form']=self.form
            template_data['title_page']='Register'
            return render(req, self.template_name, template_data)
        return redirect('/')

    def post(self, req):
        if not req.user.is_authenticated:
            template_data = {}
            if req.method == 'POST':
                self.form = Create_user_form(req.POST)
                if self.form.is_valid():
                    self.form.save()
                    return redirect('/login/')
                else:
                    template_data['reg_form'] = self.form
                    template_data['title_page'] = 'Register'
                    return render(req, self.template_name,template_data)
        return redirect('/')

#def register_page_url(req):
#    if not req.user.is_authenticated:
#        template_data={}
#        template_name="DishDecoderApp/register.html"
#        form = Create_user_form()
#        if req.method == 'POST':
#            form = Create_user_form(req.POST)
#            if form.is_valid():
#                form.save()
#                return redirect('/login/')
#    
#        template_data['reg_form']=form
#        template_data['title_page']='Register'
#        return render(req, template_name,template_data)
#    return redirect('/')

# GET: Shows the log in forms
# POST: Proves that the data introduced is from an user, autenticates the user and redirects him to the main page logged.
class login_page_url(View):
    template_name="DishDecoderApp/login.html"
    form = AuthenticationForm()
    def get(self, req):
        if not req.user.is_authenticated:
            template_data = {}
            template_data['auth_form']=self.form
            template_data['title_page']='Log in'
            return render(req, self.template_name,template_data)
        return redirect('/')
    
    def post(self, req):
        if not req.user.is_authenticated:
            template_data = {}
            username = req.POST.get('username')
            password = req.POST.get('password')
            user = authenticate(req,username=username,password=password)
            if user is not None:
                login(req,user)
                nextData = req.GET.get('next')
                if(nextData is not None):
                    return redirect(nextData)
                return redirect('/')
            else:
                messages.warning(req,'Login credentials invalid')
                template_data['auth_form']=self.form
                template_data['title_page']='Log in'
                return render(req, self.template_name,template_data)
        return redirect('/')


#def login_page_url(req):
#    if not req.user.is_authenticated:
#        template_data={}
#        template_name="DishDecoderApp/login.html"
#        form = AuthenticationForm()
#        if req.method=='POST':
#            username = req.POST.get('username')
#            password = req.POST.get('password')
#            user = authenticate(req,username=username,password=password)
#            if user is not None:
#                login(req,user)
#                return redirect('/')
#            else:
#                messages.warning(req,'Login credentials invalid')
#        template_data['auth_form']=form
#        template_data['title_page']='Log in'
#        return render(req, template_name,template_data)
#    else:
#        return redirect('/')

# GET: the user log outs

class logout_url(View):
    def get(self, req):
        if req.user.is_authenticated:
            logout(req)
        return redirect('/')

#def logout_url(req):
#    if req.user.is_authenticated:
#        logout(req)
#    return redirect('/')

# GET: the user profile where the user can go to change the password or the email
class user_profile_url(LoginRequiredMixin, View):
    login_url = '/login/'
    template_name = "DishDecoderApp/user_profile.html"
    def get(self, req):
        template_data = {}
        if Recipes.objects.filter(author=req.user.id).exists():
            created_data=Recipes.objects.filter(author=req.user.id).all()
            template_data['created_recipes']=created_data
        if Ratings.objects.filter(id_autor=req.user.id).exists():
            rating_data=Ratings.objects.filter(id_autor=req.user.id).all()
            template_data['scored_recipes']=rating_data
        template_data['title_page']='User profile'
        return render(req, self.template_name, template_data)

#@login_required(login_url='/login/')
#def user_profile_url(req):
#    template_data = {}
#    template_name = "DishDecoderApp/user_profile.html"
#    if Ratings.objects.filter(id_autor=req.user.id).exists():
#        rating_data=Ratings.objects.filter(id_autor=req.user.id).all()
#        template_data['scored_recipes']=rating_data
#    template_data['title_page']='User profile'
#    return render(req, template_name,template_data)


class change_data_url(LoginRequiredMixin, View):
    login_url = '/login/'
    template_name=""
    form_function=Change_password_form
    title_page=""

    def get(self, req):
        template_data={}
        template_data['change_data_form']=self.form_function(req.user)
        template_data['title_page']=self.title_page
        return render(req, self.template_name, template_data)


    def post(self, req):
        template_data={}
        form = self.form_function(req.user,req.POST)
        if form.is_valid():
            form.save()
            return redirect('/profile/')
        else:
            messages.warning(req,'Invalid data entered')
        return self.get(req)

#GET: Show the password change form

DishDecoderApp/templates/DishDecoderApp/basicproducts.html
{% extends 'DishDecoderApp/common.html' %}

{% block content %}

<hr>
<h1 class="display-6 text-center">Related ingredients</h1>
<hr>
{% if listedtuples %}
<div class="container">
    <div class="list-group">
        {% for tuple in listedtuples %}
        <a class="list-group-item list-group-item-action" href={% url 'basicproduct' tuple.id %}>{{tuple.name}}</a>
        {% endfor %}
    </div>
</div>
{% else %}
    <p id="Error_message">No Data Found</p>
{% endif %}

{% endblock %}

DishDecoderApp/templates/DishDecoderApp/change_email.html
{% extends 'DishDecoderApp/common.html' %}

{% block content %}

<hr>
<h1 class="display-6 text-center">Change Email</h1>
<hr>
<div class="container">

    <form method="POST" action="">{% csrf_token %}
        <div class="mb-3">
            {{ change_data_form.new_email1.label}}
            {{ change_data_form.new_email1}}
        </div>
        <div class="mb-3">
            {{ change_data_form.new_email2.label}}
            {{ change_data_form.new_email2}}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% for message in messages %}
            <p id="Error_message">{{message}}</p>
        {% endfor %}
</div>

<hr>
{% endblock %}

DishDecoderApp/templates/DishDecoderApp/common.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{{title_page}}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>  
        <link rel="stylesheet"href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" />

        <!--
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
            -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <style>
        .col-centered {
            float: none;
            margin: 0 auto;
        }

        ul {
            list-style: none;
        }

        .container {
            margin-top: 10%;
        }

        .row {
            margin-top: 5%;
        }
    </style>

</head>

<body>

    {% include 'DishDecoderApp/navbar.html' %}

    {% block content %}
        
    {% endblock %}

    


</body>

</html>

DishDecoderApp/templates/DishDecoderApp/createrecipe.html
{% extends 'DishDecoderApp/common.html' %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>  
<link rel="stylesheet"href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" />

<hr>
<h1 class="display-6 text-center">Create Your Recipe</h1>
<hr>


<form action="" method="POST">
    {% csrf_token %}
    <center>
        <div class="form-group col-md-5">
            {{ recipe_basic_form.name.label}}
            {{ recipe_basic_form.name }}
        </div>
        <h3 class="text-justify text-center">Recipe steps(Separate steps using a # for every step)</h3>
        <div class="form-group col-md-5">
            {{ recipe_basic_form.steps.label}}
            {{ recipe_basic_form.steps }}
        </div>
        <div class="form-group col-md-5" id="forms">
            <!--{% for form in formset %}
                {{ form }} 
            {% endfor %}-->
        </div>
        {{ formset.management_form}}
        <!--<input type="button" value="Add More" id="add_form">-->
        <a href="javascript:void(0)" id="add_form">Add Another Ingredient</a>
        <a href="javascript:void(0)" id="erase_form">Erase Another Ingredient</a>

        <script>
            var form_count = {{ formset.total_form_count }};
            $('#add_form').click(function(){
                console.log(form_count);
                var new_form = '{{formset.empty_form|escapejs}}'.replace(/__prefix__/g,form_count);
                $('#forms').append(new_form);
                form_count++;
                $('#id_form-TOTAL_FORMS').val(form_count);
            });

            $('#erase_form').click(function(){
                console.log("You clicked erase!")
                $('#id_form-'+(form_count-1)+'-quantity').parent().parent().remove();
                $('#id_form-'+(form_count-1)+'-id_product').parent().parent().remove();
                if(form_count>1){
                    form_count--;
                    $('#id_form-TOTAL_FORMS').val(form_count);
                }
                console.log(form_count);
            });
        </script>

<!--var new_form = '{{formset.empty_form|escapejs}}'.replaceAll('id_form-0-id_product', 'id_form-'+form_count+'-id_product').replaceAll('id_form-0-quantity', 'id_form-'+form_count+'-id_quantity');-->
        <!--<div class="container">
            <h2 class="text-center">Select the Ingredients</h2>
            {% if prod %}
            <div class="form-group col-md-4 mx-auto">
                <select class="form-control" id="exampleFormControlSelect1">
                    {% for ingredient in prod %}
                    <a class="list-group-item list-group-item-action">
                        <option>{{ingredient.name}}</option></a>
                    {% endfor %}
                </select>
            </div>
        </div>
        {% else %}
                <p id="Error_message">No Data Found</p>
        {% endif %}-->
    </center>
    <br>
    <center><button type="submit" class="btn btn-success btn-lg">Create recipe</button></center>
    <br>
</form>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}

DishDecoderApp/templates/DishDecoderApp/edit_recipe.html
{% extends 'DishDecoderApp/common.html' %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>  
<link rel="stylesheet"href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" />

<hr>
<h1 class="display-6 text-center">Edit your Recipe</h1>
<hr>
<div class="container" id="nameEditForm">
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group col-md-5">
        <h3> Name: {{ recipe_data.name }}</h3>
        {{ recipe_form.name }} <button type="submit" id="name_change_btn">Change Name</button> 
    </div>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        {% if message.message == 'Incorrect name' %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endif %}
    {% endfor %}
</ul>
{% endif %}
</div>
<div class="container" id="stepEditForm">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group col-md-5">
            <h3> Steps: {{ recipe_data.steps }}</h3>
            {{ recipe_form.steps }} <button type="submit" id="steps_change_btn">Change Steps</button> 
        </div>
    </form>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
        {% if message.message == 'Incorrect steps' %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endif %}
    {% endfor %}
</ul>
{% endif %}
</div>
<div class="container" id="ingredientsEditForm">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="col-md-5">
        <table>
            {% for form in ingredients_forms %}
                {{ form }} 
            {% endfor %}
        </table>
        </div>
        <div class="col-md-5" id="forms"></div>
        {{ ingredients_forms.management_form}}
        <a href="javascript:void(0)" id="add_form">Add Another Form</a>
        <a href="javascript:void(0)" id="erase_form">Erase Another Form</a>
        <button type="submit" id="ing_change_btn">Change ingredients</button>
    </form>
</div>


        <script>
            var form_count = {{ ingredients_forms.total_form_count }};
            $('#add_form').click(function(){
                //form_count++;
                var new_form = '{{ingredients_forms.empty_form|escapejs}}'.replace(/__prefix__/g,form_count);
                $('#forms').append(new_form);
                form_count++;
                $('#id_form-TOTAL_FORMS').val(form_count);
            });

            $('#erase_form').click(function(){
                console.log("You clicked erase!")
                $('#id_form-'+(form_count-1)+'-quantity').parent().parent().remove();
                $('#id_form-'+(form_count-1)+'-id_product').parent().parent().remove();
                if(form_count>0){
                    form_count--;
                    $('#id_form-TOTAL_FORMS').val(form_count);
                }
                console.log(form_count);
            });
        </script>

{% if messages %}
<ul class="messages" id="error_messages">
    {% for message in messages %}
        {% if message.message != 'Incorrect name' and message.message != 'Incorrect email' %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endif %}
    {% endfor %}
</ul>
{% endif %}


{% endblock %}

DishDecoderApp/templates/DishDecoderApp/extrecipe.html
{% extends 'DishDecoderApp/common.html' %}
{% block content %}

<div text-align="center" align-items="center" >

    <h1 text-align="center">{{title}}</h1>

    <a href="{{href}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" text-align="center">Go to recipe web page</a>

    <h1 text-align="center">Ingredients</h1>
    {% if ing %}
    <h1 text-align="center">{{ing}}</h1>
    {% else %}
    <h3 text-align="center">Check the web site for more information about the ingredients.</h3>
    {% endif %}

</div>
{% endblock %}

DishDecoderApp/templates/DishDecoderApp/login.html
{%  extends 'DishDecoderApp/common.html' %}
{% block content %}


<html>
    <head>
        <title>Log in</title>
    </head>
    <h3 style="text-align: center;">Log in</h3>

    <form style="text-align: center;" method="POST" action="">

        {% csrf_token %}
    <div style="margin-top: 100px; border-radius: 25px; padding: 20px;">
        <div class="text-center">
            <p><b>Username</b></p>
            {{auth_form.username}}
        </div>
        <div class="text-center">
        <p><b>Password</b></p>
        {{auth_form.password}}
        </div>
        <input style="margin-top: 10px" type="submit" name="Log in" id="submit-login">
    </div>
    </form>
    {% for message in messages %}
        <p id="Error_message">{{message}}</p>
    {% endfor %}
    <p class="text-center">If you are not Registered go click <a href="/register"> Here</a></p>
</html>
{% endblock %}

DishDecoderApp/templates/DishDecoderApp/main.html
{% extends 'DishDecoderApp/common.html' %}

{% block content %}
<script>
    $(function () {
        $("#id_recipe_title").autocomplete({
            source: function (request, response) {
                $.ajax({
                    "url": "https://recipe-puppy.p.rapidapi.com/",
                    "headers": {
                        'x-rapidapi-key': "{{ api_key }}",
                        'x-rapidapi-host': "recipe-puppy.p.rapidapi.com"
                    },
                    "type": "GET",
                    "data": {
                        "q": request.term,
                    },
                    success: function (data) {
                        var data = jQuery.parseJSON(data);
                        response($.map(data.results, function (item) {
                            return {
                                label: item.title,
                                value: item.title,
                                title: item.title,
                                href: item.href,
                                ing: item.ingredients
                            }
                        }));
                    }
                });
            },
            minLength: 3,
            select: function (event, ui) {
                if (ui.item) {
                    $("#id_recipe_title").val(ui.item.title);
                    $("#id_recipe_href").val(ui.item.href);
                    $("#id_recipe_ing").val(ui.item.ing);
                }
            }
        });
    });
</script>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-centered">
            <h1>Search in our database</h1>
            <div class="card card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    {{ field }}
                    {% endfor %}
                    <input type="submit" name="submit" value="Search" />
                </form>
            </div>
        </div>
        <div class="col-md-4 col-centered" id="autocomplete-div">
            <h1>Search external recipe</h1>
            <div class="card card-body">
                <form method="post" enctype="multipart/form-data" action="" class="col-centered">
                    {% csrf_token %}
                    {% for field in aform %}
                    {{ field }}
                    {% endfor %}
                    <input type="submit" value="Search" />
                </form>
            </div>
        </div>
        <div class="col-md-4 col-centered">
            <h1>Create recipe</h1>
            <div class="card card-body">
                <a id="create-btn" class="btn btn-primary col-centered" href={% url 'createrecipe' %}>Create Recipe</a>
            </div>
            <div class="card card-body">
                <a id="edit-btn" class="btn btn-primary col-centered" href={% url 'listeditrecipe' %}>Edit Recipe</a>
            </div>
            <div class="card card-body">
                <a id="erase-btn" class="btn btn-primary col-centered" href={% url 'listeraserecipe' %}>Erase Recipe</a>
            </div>
        </div>

    </div>




</div>

{% endblock %}